# Generated by Django 3.2.7 on 2021-11-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.TextField()),
                ('grade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('included', models.TextField()),
                ('date_of_departure', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('take_with_you', models.TextField()),
                ('tour_features', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorytour', to='place.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourcompany', to='place.company')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pictures/%Y/%m/%d/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourphoto', to='place.tour')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='place.tour')),
            ],
            options={
                'verbose_name': 'Фото туров',
                'verbose_name_plural': 'Фото туров',
            },
        ),
        migrations.CreateModel(
            name='Tour_abroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('required_documents', models.TextField()),
                ('date', models.DateTimeField()),
                ('tour_features', models.TextField()),
                ('places_of_visit', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyabroad', to='place.company')),
            ],
            options={
                'verbose_name': 'За границей',
                'verbose_name_plural': 'За границей',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programtour', to='place.tour')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='place.company')),
            ],
        ),
    ]
