# Generated by Django 3.2.7 on 2021-12-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_rating_ratingstar_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='general_tour',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='individual_tour',
            field=models.BooleanField(default=True),
        ),
    ]
