# Generated by Django 3.2.7 on 2021-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='telefon_company',
            field=models.URLField(null=True),
        ),
    ]
