# Generated by Django 3.2.7 on 2021-12-23 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0006_tour_telefon_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_tour', models.CharField(default='', max_length=2047)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('В ожидании доставки', 'In Pending'), ('Успешно доставлен', 'Succsess'), ('Отменён', 'Canceled')], default='В ожидании доставки', max_length=50)),
                ('sum_price', models.PositiveIntegerField(default=0, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.cart', verbose_name='Корзина')),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='telefon_company',
            new_name='book_your_place',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='tour',
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='place.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='tourphoto',
            name='tour_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_photo', to='place.tour'),
        ),
        migrations.AlterField(
            model_name='tourphoto',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='OrderTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tours', to='place.order')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tours', to='place.tour')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tours',
            field=models.ManyToManyField(through='place.OrderTour', to='place.Tour'),
        ),
        migrations.CreateModel(
            name='CartTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttour', to='place.cart')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttours', to='place.tour')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_tour',
            field=models.ManyToManyField(related_name='tours', through='place.CartTour', to='place.Tour'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
