# Generated by Django 3.2.7 on 2021-12-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20211223_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blabal', to='place.tour'),
        ),
    ]
