# Generated by Django 3.2.7 on 2021-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_order_cart_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttour',
            name='general_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carttour',
            name='quantity_tour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='amount',
            field=models.PositiveIntegerField(default=18, null=True, verbose_name='Количество мест'),
        ),
    ]
