# Generated by Django 3.2.7 on 2021-12-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20211223_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertour', to='place.tour'),
        ),
    ]
