# Generated by Django 3.2.7 on 2021-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_alter_orders_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колличество'),
        ),
    ]
