# Generated by Django 3.2.7 on 2021-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество мест'),
        ),
    ]
